Feat: Post 도메인 이미지 업로드 테스트 코드 구현
MTVS-Noblesse/Triplay-backend pull request #31
Opened 2024-09-04 15:06 UTC by kamillee0918

## ⭐Key Changes
> 핵심 변경 사항에 대해서 적어주세요.
1. 포스트 추가 / 조회 / 수정 / 삭제 관련 테스트 코드를 추가했어요...

<br>

## 📌Issue
> 닫을 issue 번호 : resolved #30

<br>

## 🩼Branch
> 반영 branch feat-30 -> dev

<br>

## 👪To Reviewers
> reviewer에게 하고 싶은 말을 적어주세요.
* 코드 리뷰 부탁드려요...

2024-09-09 17:03 UTC, kamillee0918 commented
Post 도메인, 이미지 업로드 로직을 개선했어요..

수정이 필요한 부분이 있으면 말씀해 주세요.. ㅠ

2024-09-11 00:42 UTC, Hexeong commented on src/main/java/com/noblesse/backend/post/api/command/PostCommandController.java
> +            @RequestParam("userId") Long userId,
form data로 userId를 넘기는 방법은 보안상 안좋을 것 같아서 해당 유저가 가지고 있는 토큰에서 userId를 추출하는 방식으로 가져와야 될 것 같습니다..!

2024-09-11 00:43 UTC, Hexeong commented on src/main/java/com/noblesse/backend/post/api/command/PostCommandController.java
> +            @RequestParam("userId") Long userId
여기 또한 토큰에서 userId 추출하는 방식으로 부탁드립니다

2024-09-11 01:12 UTC, Hexeong requested changes
userId를 사용하는 방식만 고치면 될 것 같습니다 :)

2024-09-11 14:23 UTC, kamillee0918 commented
말씀하신 요구 사항에 충족(?)되는 코드를 리팩토링 했어요..! 코드 리뷰 부탁드립니다.. :)

2024-09-12 00:23 UTC, Hexeong approved these changes
LGTM :)

2024-09-12 00:24 UTC, merged